version: "3"

services:
  ftp-server:
    build: .
    environment:
        ADDRESS: 
        ROOT_DIR: /home/ftp
    ports:
      - 20-21:20-21
      - 21000-21100:21000-21100
      - 989-990:989990
    restart: always
